name: Pylint Linter

on:
  push:
    branches: [ "master" ]  # Replace with your branch name if different
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        run: |
          # Replace 'src' with the directory where your Python files are located
          pylint src/**/*.py
